# Generated by Django 5.2.13 on 2026-05-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the Event you want to share', max_length=2000)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(blank=True, choices=[('t', 'Trabajo Educativo Social'), ('a', 'School Activity'), ('r', 'Random'), ('s', 'Sport')], default='a', help_text='Event type', max_length=1)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(help_text="Enter submitter's name", max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(help_text='Enter a brief description of the memory you wish to share', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='memory_gallery/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(help_text='Enter a brief Biography of the student, including future aspirations', max_length=2000)),
                ('quote', models.CharField(help_text='enter a quote that represents you', max_length=500, null=True)),
                ('song', models.CharField(help_text='enter a song that represents your senior year', max_length=100, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter mr. ms. or mrs.', max_length=4)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.CharField(help_text="enter a brief description of the teacher's role for the seniors", max_length=200)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='yearbook.event')),
            ],
        ),
    ]
