# Generated by Django 6.0 on 2026-06-04 03:10

import yearbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=yearbook.models.event_image_path),
        ),
    ]
