# Generated by Django 5.2.13 on 2026-06-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
