# Generated by Django 5.2.13 on 2026-06-04 13:43

import yearbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0003_rename_image_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=yearbook.models.event_image_path),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students_gallery/'),
        ),
    ]
