# Generated by Django 5.2.13 on 2026-06-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_alter_eventimage_image'),
        ('yearbook', '0004_alter_eventimage_image_alter_memory_image'),
    ]

    operations = [
    ]
