# Generated by Django 5.2.13 on 2026-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0005_merge_20260605_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='future_plans',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
