# Generated by Django 5.2.13 on 2026-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0006_student_future_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='future_plans',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
