# Generated by Django 5.2.13 on 2026-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0007_alter_student_future_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
    ]
