# Generated by Django 5.2.13 on 2026-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0008_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='biography',
            field=models.TextField(help_text='Enter a brief Biography of the teacher, including future aspirations', max_length=2000, null=True),
        ),
    ]
