# Generated by Django 5.2.13 on 2026-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0009_teacher_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memory_gallery/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students_gallery/'),
        ),
    ]
